# Numpy Assignment

### Write a function so that the columns of the output matrix are powers of the input
vector.

In [1]:
import numpy as np

In [6]:
def getOutput(vector):
    print(np.vander(vector))
    
    

In [7]:
getOutput([1,2,3,4])

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


## moving avg

In [28]:
def moving_avg(x,window_size):
    list1=[]
    val=len(x)-window_size+1
    for i in range(val):
        a=x[i:window_size+i]
        list1.append(np.sum(a)/window_size)
    print(list1)      
        
    

In [29]:
moving_avg([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150],3)

[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
